### ISSUE TITLE
Issue with generated samples-reg

### ISSUE THREAD

**Issue by MaheswarMaji** [SmartTURB/diffusion-lagr#1]
Whenever I try to generate sample trajectories following the prescribed details in the README file, it generates a file named "samples_179200x801x2000x3.npz" instead of "samples_179200x2000x3.npz". It has shape [179200x801x2000x3]. The extra 801 is being picked up from diffusion flag entry diffusion steps. What could be possible reason for this anomaly and please suggest resolution thereof. Further, if we try to test the model for two dimensional trajectories, what are the changes we need to make in the flags or code. Thanks in advance.

**Comment by TianyiLi-92** [comment]
Hi,

Thanks for reporting the issues. The problem has been fixed by simply commenting and uncommenting some lines in [`scripts/turb_sample.py`](https://github.com/SmartTURB/diffusion-lagr/commit/77da6cdc67775aa45af6c4148068f00a75e54c41), which has been implemented.

About two-dimensional trajectories, do you mean with shape `(num_trajectories, length, 2)`? If so, you can replace the `in_channels` from 3 to 2.

Feel free to ask us if there is still anything unclear.

**Comment by MaheswarMaji** [comment]
Thanks a lot.
